---
title: Elan Jones
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
url: http://elanmaijones.com
permalink: pretty
exclude:
- bower_components
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
description: London-based Casting Director for film and television
company: Elan Jones
email: info@elanmaijones.com
facebook: 
instagram: 
twitter: 
imdb: 
vimeo: 
linkedin: 
googleplus: 
googleanalytics: UA-83447045-1
verification: 2dBSz2bmoTAHVn3LQ1_zKyDyyErePCDTzHYCLMFIf2A
logo: "/assets/img/layout/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
